# /etc/systemd/system/live-subtitle-relay.service.d/egress.conf
[Unit]
Requires=live-subtitle-relay-egress.service
After=live-subtitle-relay-egress.service
BindsTo=live-subtitle-relay-egress.service
PartOf=live-subtitle-relay-egress.service
